### ISSUE TITLE
PHP V7.3

### ISSUE THREAD

**Issue by lukasmairl** [billbeeio/billbee-php-sdk#14]
Ich habe ein PHP v7.3 upgrade durchgeführt und erhalte nun die nachfolgende Fehlermeldung. Ich verwende die neuesten Versionen von ObjectMapper und JsonSerializer

Fatal error: Uncaught Error: Call to a member function critical() on null in /src/Client.php:92 Stack trace: #0 /test.php(26): BillbeeDe\BillbeeAPI\Client->__construct('...') #1 {main} thrown in /.../src/Client.php on line 92

        try {
            $this->jom = new ObjectMapper(new JsonSerializer());
        } catch (\Exception $ex) {
            $this->logger->critical('Object Mapper could not be created.');
        }
        $this->setLogger($logger);

**Comment by devtronic** [comment]
Danke für die Info, wird geprüft.

**Comment by devtronic** [comment]
Versuche bitte einmal mit `composer update` die Abhängigkeiten zu aktualisieren.

**Comment by lukasmairl** [comment]
Hallo,
hab ich gemacht und dann den pull request #15 rein-gemerged. Jetzt hats aber was mit 
dem Doctrine/AnnotationReader. 

opcache.save_comments=1  oder zend_optimizerplus.save_comments=1 kann ich aber leider nicht auf 1 setzen. Ist derzeit auf 0. 

Schaut so aus als ob nur ich das Problem habe. Ich hab im Moment mal php auf 7.2 downgegraded Zumindest läuft mal alles wieder.

Danke 


Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.save_comments=1 or zend_optimizerplus.save_comments=1. in /vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:183 Stack trace: #0 /test/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(187): Doctrine\Common\Annotations\AnnotationException::optimizerPlusSaveComments() #1 /test/vendor/mintware-de/data-model-mapper/src/ObjectMapper.php(66): Doctrine\Common\Annotations\AnnotationReader->__construct(Object(Doctrine\Common\Annotations\DocParser)) #2 /test/vendor/billbee/billbee-api/src/Client.php(92): MintWare\DMM\ObjectMapper->__construct(Object(MintWare\DMM\Serializer\JsonSerializer)) #3 /test/test.php(28): BillbeeDe\BillbeeAPI\Client->__construct('...', '....', '...') #4 {main} N in /vendor/mintware-de/data-model-mapper/src/ObjectMapper.php on line 68

**Comment by devtronic** [comment]
Alles klar, dann liegt es tatsächlich an deinen PHP Einstellungen.

Um das Problem zu lösen musst du entweder die Einstellungen entsprechend setzen (was, wie du schreibst, in deinem Fall nicht möglich ist), oder die `Zend Optimizer+` und `Zend OPcache` PHP Erweiterung deaktivieren.
