### ISSUE TITLE
Search for products (etc) don't return data.

### ISSUE THREAD

**Issue by TiBianMod** [billbeeio/billbee-php-sdk#22]
I'm trying to use the search endpoint "/api/v1/search".

The response from the server has "status Code: 200", but i don't see anywhere related data with the search.

```php
use BillbeeDe\BillbeeAPI\Client;

$user = Config::get('BILLBEE_USER');
$apiPassword = Config::get('BILLBEE_API_PASSWORD');
$apiKey = Config::get('BILLBEE_API_KEY');

$client = new Client($user, $apiPassword, $apiKey);

$response = $client->post('search', [
    'form_params' => [
        'Type' => 'product',
        'Term' => 'title:"samsung"',
    ]
]);
```

### Here is the response from the server.
```php
Response {#5671 ▼
  -reasonPhrase: "OK"
  -statusCode: 200
  -headers: array:11 [▶]
  -headerNames: array:11 [▶]
  -protocol: "1.1"
  -stream: Stream {#5691 ▶}
}
```

**Comment by devtronic** [comment]
This endpoint is not implemented at the moment. Check out my comment here: https://github.com/billbeeio/billbee-php-sdk/issues/21#issuecomment-549313926

**Comment by devtronic** [comment]
The search call will be available with the next release of the sdk

**Comment by TiBianMod** [comment]
Very Nice, Thanks :)
