### ISSUE TITLE
Search returns deleted records.

### ISSUE THREAD

**Issue by TiBianMod** [billbeeio/billbee-php-sdk#27]
Hi @devtronic,

I found a small issue with the search api, let me explain please.

for example, let's search for a SKU.

```php
$client = App\API\Billbee\Client::init();

$client->search('70-CM6C-PWRQ');
```

**In this example, exist 3 Products with the same SKU, the 2 products of this example was deleted from us, you can't see the 2 last ids on Billbee UI.**

```php
array:3 [▼
  0 => BillbeeDe\BillbeeAPI\Model\Search\ProductResult {#5951 ▼
    +id: 22817443
    +shortText: "Osram SuperStar Halogen-Röhre, R7S-Sockel, dimmbar, 120 Watt - Ersatz für 150 Watt, Warmweiß - 2900K"
    +sku: "70-CM6C-PWRQ"
    +tags: ""
  }
  1 => BillbeeDe\BillbeeAPI\Model\Search\ProductResult {#5940 ▼
    +id: 22390094
    +shortText: "Osram SuperStar Halogen-Röhre, R7S-Sockel, dimmbar, 120 Watt - Ersatz für 150 Watt, Warmweiß - 2900K"
    +sku: "70-CM6C-PWRQ"
    +tags: ""
  }
  2 => BillbeeDe\BillbeeAPI\Model\Search\ProductResult {#5938 ▼
    +id: 21635548
    +shortText: "Osram SuperStar Halogen-Röhre, R7S-Sockel, dimmbar, 120 Watt - Ersatz für 150 Watt, Warmweiß - 2900K"
    +sku: "70-CM6C-PWRQ"
    +tags: ""
  }
]
```

Now of course in this point we don't know which record of this results exist or not, because if you decide to make a patch or get request or something with this record that is already deleted, then in this point we have a problem.

let's make a simple get request to retrieve the last product on array.

```php
$client = App\API\Billbee\Client::init();

$client->getProduct(21635548);
```

>Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://app.billbee.io/api/v1/products/21635548?lookupBy=id` resulted in a `404 Not Found`

My proposal is...
or you hide the deleted records from the search results.
or you include in the response a property isDeleted or isActive or something to indicate if the record is live or not.

Thank you in advance.

**Comment by devtronic** [comment]
At the moment there is no clean up task for the search index. This has nothing to do with the SDK. 
I've created a ticket for our backend devs.
