### ISSUE TITLE
Request of a new Delete Product Endpoint.

### ISSUE THREAD

**Issue by TiBianMod** [billbeeio/billbee-php-sdk#29]
Hi again @devtronic,

I find very useful a delete endpoint of a product.
>DELETE /api/v1/products/{id}

In case for example we want to delete one product from our online shop, we can send a delete request to Billbee to delete this product also. So we have always sync catalog.

Thank you in advance.

**Comment by devtronic** [comment]
Endpoint implemented. Waiting for rollout

**Comment by devtronic** [comment]
I'll publish a new release which includes the new delete call today.
This call will work from the next update tomorrow morning.
