### ISSUE TITLE
Missing properties on Product Model.

### ISSUE THREAD

**Issue by TiBianMod** [billbeeio/billbee-php-sdk#30]
Hi again @devtronic,

After a quick check on Billbee API, i realised that, they are missing properties on Product Model.

>Base on the POST /api/v1/products
The missing properties are...
```
Condition
WidthCm
LengthCm
HeightCm
BillOfMaterial
```

This means, that i can't interact with this properties, if I make a get/post or patch request.

Thank you in advance.

**Comment by devtronic** [comment]
Will be available during the next package update.
