### ISSUE TITLE
Null-Pruefung im Konstruktor bei Model Stock 

### ISSUE THREAD

**Issue by jkahnt** [billbeeio/billbee-php-sdk#4]
Hallo,

zuallerst großes Lob für den umfangreichen API Client. Bis jetzt konnte ich damit wunderbar arbeiten allerdings viel mir eine Kleinigkeit auf. Wenn ich ein Objekt vom Typ Stock erstelle und im Konstruktor für NewQuantity den Wert 0 übergebe wird dieser nicht akzeptiert bzw. mit dem Wert von OldQuantity überschrieben. Mein Workaround aktuell ist nach dem Konstruktor-Aufruf nochmal die SetNewQuantity-Methode verwende um den Wert 0 übertragen zu können(da wird nicht auf null geprüft). Wäre es dann nicht besser die Prüfung in Zeile 62 von (newQuantity == null) auf (newQuantity === null) anzupassen. Dann könnte man sich den Extra-Aufruf sparen.

**Comment by Devtronic** [comment]
Danke für das Lob. Du hast natürlich recht, ich passe das entsprechend an.

**Comment by Devtronic** [comment]
Ist mit 26b435f508c / v1.1.2  gefixt, einfach mit `composer update` die aktuelle Version ziehen.
