### ISSUE TITLE
Default initialization of shippingProductId leads to server error

### ISSUE THREAD

**Issue by JensMe** [billbeeio/billbee-php-sdk#41]
Hi @devtronic,
I noticed an issue with the SDK's code when creating a new product in Billbee with the API endpoint "POST /api/v1/products". First, I did not initiate the Product's field shippingProductId. Therefore, the PHP SDK used the integer "0" as default. However, the Billbee API responded an server error: 
- Error Code: 8
- Error Message: The given ShippingProductId does not match any shipping provider product.

When explicitly initiating the field shippingProductId as "null", the Billbee endpoint accepts my request. Ironically, the request's response specifies the shippingProductId to be the integer "0" instead of "null" but when requesting the newly created product with the API endpoint "GET /api/v1/products/{id}", it shows "null" instead of the integer "0". 

Hence, I propose to initiate that field with "null" instead of an integer "0" by default. I hope this eases the use of this SDK for others.

**Comment by devtronic** [comment]
Thanks for the information. You're right. The field should be initialized with `<NULL>`.

**Comment by JensMe** [comment]
I witnessed another initialization issue. The product's field "condition" is initialized as "brand new" in the SDK, even though the Swagger UI returns "null" as default. Hence both systems differ on their output.

**Comment by devtronic** [comment]
Fixed in [v2.2.0-RC1](https://packagist.org/packages/billbee/billbee-api#v2.2.0-RC1)
