### ISSUE TITLE
patchable fields for products

### ISSUE THREAD

**Issue by schelmo** [billbeeio/billbee-php-sdk#43]
hi,
why are there so few fields to patch a product?
like updating the prices, title, materials, tags, widthCm, lengthCm, heightCm.
would be really handy, to reflect changes in the shop system.

**Comment by JensMe** [comment]
Hi @schelmo,
thanks for raising this issue. We witnessed the same! For us it is a pity that neither prices and the sources are patchable. About half a year ago we contacted the Billbee Support, however, they rejected our request. @devtronic Please forward this change request internally to the Billbee development team. The current function is really limiting! Many thanks. :)

**Comment by schelmo** [comment]
Hi @JensMe 
here is the same issue: https://roadmap.billbee.io/b/optimierungen-schnittstellen/billbee-api-produkte-aktualisieren
Just upvoted it ;)

**Comment by devtronic** [comment]
Waiting for the voting result. If the feature is implemented in the API, we also add it to the SDK.

**Comment by Yuri-Lima** [comment]
I have experienced the same frustration whe i tried to patch a product. I got the ErrorMessage:
`"Property InvoiceText does not exist or is not patchable\nProperty Title does not exist or is not patchable\nProperty BasicAttributes does not exist or is not patchable\nProperty Images does not exist or is not patchable\nProperty VatIndex does not exist or is not patchable\nProperty Price does not exist or is not patchable\nProperty CostPrice does not exist or is not patchable\nProperty Vat1Rate does not exist or is not patchable\nProperty Vat2Rate does not exist or is not patchable\nProperty StockDesired does not exist or is not patchable\nProperty StockCurrent does not exist or is not patchable\nProperty StockWarning does not exist or is not patchable\nProperty Materials does not exist or is not patchable\nProperty Sources does not exist or is not patchable\nProperty StockCode does not exist or is not patchable\nProperty StockReduceItemsPerSale does not exist or is not patchable\nProperty Stocks does not exist or is not patchable\nProperty Category2 does not exist or is not patchable\nProperty Category3 does not exist or is not patchable\nProperty UnitsPerItem does not exist or is not patchable\nProperty SoldAmount does not exist or is not patchable\nProperty SoldSumGross does not exist or is not patchable\nProperty SoldSumNet does not exist or is not patchable\nProperty SoldSumNetLast30Days does not exist or is not patchable\nProperty SoldSumGrossLast30Days does not exist or is not patchable\nProperty SoldAmountLast30Days does not exist or is not patchable\nProperty IsDigital does not exist or is not patchable\nProperty IsCustomizable does not exist or is not patchable\nProperty DeliveryTime does not exist or is not patchable\nProperty Recipient does not exist or is not patchable\nProperty Occasion does not exist or is not patchable\nProperty CountryOfOrigin does not exist or is not patchable\nProperty ExportDescription does not exist or is not patchable\nProperty ExportDescriptionMultiLanguage does not exist or is not patchable\nProperty TaricNumber does not exist or is not patchable\nProperty Condition does not exist or is not patchable\nProperty WidthCm does not exist or is not patchable\nProperty LengthCm does not exist or is not patchable\nProperty HeightCm does not exist or is not patchable\nProperty BillOfMaterial does not exist or is not patchable\nProperty Type does not exist or is not patchable\nProperty CustomFields does not exist or is not patchable\nProperty IsDeactivated does not exist or is not patchable"`


What makes the BillBee team not update all the input fields? At least for now does not make any sense.
Please, in case you have plans of implmenting let us know! 

Thank you
