### ISSUE TITLE
No way to patch line2 and 3 of an address

### ISSUE THREAD

**Issue by nobyna** [billbeeio/billbee-php-sdk#53]
There ist no way, to patch die fields line2 and line3 of an address. The only way, to patch an address is using the model für costumerAddress. But the model of costumerAddress is different to the model of addess that is used by the order endpoint. The fields line2 and line3 are missing in the costumerAddress model.

It would be nice, if you can add an endpoint to patch an address, that uses address n´modell or you add the line2 and 3 to the costumerAddress model.

**Comment by devtronic** [comment]
Billbee does not store line2 and line3 separately. Line2 and line3 are stored concatenated inside AddressAddition
