### ISSUE TITLE
Issue in express shipping with  /api/v1/shipment/shipwithlabel

### ISSUE THREAD

**Issue by wdraghwendra** [billbeeio/billbee-php-sdk#54]
We are trying to hit the POST  api/v1/shipment/shipwithlabel API for DHL Express. Our request is 
{
  "OrderId": xxx, // billbee order
  "ProviderId": 20000000000012103, // DHL express provider id
  "ProductId": 20000000000083776 // DHL express product id
} 

Always I am getting this response : 
{
  "ErrorMessage": "Bitte einen Verpackungstyp auswählen",
  "ErrorCode": 22,
  "ErrorDescription": "InvalidShippingServices",
  "Data": null
}
IT is not working with swagger also https://app.billbee.io//swagger/ui/index#!/Shipments/Shipment_ShipWithLabel
The DHL standards and international is working well but not DHL express anyone would like to share the answer?

**Comment by devtronic** [comment]
Some providers also requires the dimensions of a shipment. You've to assign a package type to the order. 

The assignment of package types to orders is only possible in the Billbee GUI.
1. Create a package type: https://app.billbee.io/app_v2/settings/shipping/packagetypes
2. Edit a order and assign it in the "Versand" tab
