### ISSUE TITLE
ShipmentType in Shipment model is missing

### ISSUE THREAD

**Issue by knaepel** [billbeeio/billbee-php-sdk#56]
Hello,

I am currently implementing the connection to Otto. Otto needs a return number so that an order can be marked as shipped.

Via the API directly it is possible to transfer the **ShipmentType** at a **Shipment**. This is also documented in the API (https://app.billbee.io//swagger/ui/index?_ga=2.159967226.630000559.1645533049-183265745.1645533049#!/Orders/OrderApi_AddShipment).

But the field is missing in the shipment class.

**Comment by devtronic** [comment]
Fix in [v2.2.0-RC1](https://packagist.org/packages/billbee/billbee-api#v2.2.0-RC1)
