### ISSUE TITLE
Dependencies outdated for modern frameworks

### ISSUE THREAD

**Issue by cainytheslave** [billbeeio/billbee-php-sdk#60]
I am building a custom Laravel Application and would love to use the SDK but unfortunately there are multiple dependencies that are too low in order for it to install with composer.

- SDK needs guzzle version 6.3 but Laravel uses 7.0
- SDK needs psr/log 1.1 but Laravel uses 3.0.0

Question 1: Is is easy to fork the project and make the changes so the SDK can use the newer Versions?
Question 2: Is it possible to just use both versions in my composer in order to support the SDK as well as Laravel?

What would be your approach when you got such a problem? Any help appreciated.

**Comment by devtronic** [comment]
psr/log Constraint was updated in v2.1.0
https://packagist.org/packages/billbee/billbee-api#v2.1.0
