### ISSUE TITLE
The PSR Http Message implementation may return NULL for getHeader()

### ISSUE THREAD

**Issue by agoradesign** [billbeeio/billbee-php-sdk#66]
The docs for Psr\Http\Message\MessageInterface::getHeader() clearly say: "If the header does not appear in the message, this method MUST return an empty array."

The current implementation however may return NULL, which led to problems for me in our Drupal integration (causing PHP warnings)

**Comment by devtronic** [comment]
We don't implement the MessageInterface. Could you please provide a stack trace of the error?

**Comment by agoradesign** [comment]
sorry for the noise - I've mixed up the repos last year and seem to forgot to close this issue here -> see https://github.com/billbeeio/custom-shop-php-sdk/issues/12 for the correct issue
