### ISSUE TITLE
Name des JsonFields in Order.php inkorrekt

### ISSUE THREAD

**Issue by JensMe** [billbeeio/billbee-php-sdk#7]
Liebes Entwickler-Team,

in der Klasse /Model/Order.php ist für das Attribut `$adjustmentCost` beim Namen für das JsonField-Mapping `TotalCost` hinterlegt. Laut API müsste der Name jedoch `AdjustmentCost` lauten. 

Viele Grüße
Jens

**Comment by Devtronic** [comment]
Danke für den Hinweis. Ein klarer Fall von Copy-Pasta 😅
