### ISSUE TITLE
Error in SoldProduct Serialization

### ISSUE THREAD

**Issue by Reflic** [billbeeio/billbee-php-sdk#73]
The SoldProduct Properties can be "null" if this is a discount position or something else.

 BillbeeDe\BillbeeAPI\Model\SoldProduct::getSkuOrId(): Return value must be of type string, null returned

  at C:\Users\refli\Projekte\beeconnect\vendor\billbee\billbee-api\src\Model\SoldProduct.php:184
    180▕     }
    181▕
    182▕     public function getSkuOrId(): string
    183▕     {
  ➜ 184▕         return $this->skuOrId;
    185▕     }
    186▕
    187▕     public function setSkuOrId(string $skuOrId): self
    188▕     {

I am happy to help again!

**Comment by devtronic** [comment]
Sorry for the late response. We fixed this bug in the past but unfortunately forgot to create a new release. We've published v2.2.1 which includes the fix for this problem.

https://github.com/billbeeio/billbee-php-sdk/releases/tag/v2.2.1
